import sqlite3


DB = "data/opensentinel.db"


def get_connection():
    return sqlite3.connect(DB)


def create_database():

    conn = get_connection()
    cursor = conn.cursor()

    # Users who can access OpenSentinel
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS users
        (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            role TEXT NOT NULL,
            email TEXT UNIQUE
        )
        """
    )

    # Security events received from logs
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS events
        (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT,
            source_ip TEXT,
            username TEXT,
            event_type TEXT,
            status TEXT
        )
        """
    )

    # Security alerts generated by the analyzer
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS alerts
        (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            type TEXT,
            ip TEXT,
            attempts INTEGER,
            risk_score INTEGER,
            severity TEXT,
            detection_method TEXT,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
        """
    )

    # IPs temporarily/permanently blocked by the response engine
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS blocked_ips
        (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            alert_id INTEGER,
            ip_address TEXT NOT NULL,
            blocked_at TEXT DEFAULT CURRENT_TIMESTAMP,
            blocked_until TEXT,
            status TEXT DEFAULT 'ACTIVE',
            FOREIGN KEY (alert_id) REFERENCES alerts(id)
        )
        """
    )

    # Actions performed by administrators/analysts
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS actions
        (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            alert_id INTEGER,
            user_id INTEGER,
            action_type TEXT,
            remarks TEXT,
            action_time TEXT DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (alert_id) REFERENCES alerts(id),
            FOREIGN KEY (user_id) REFERENCES users(id)
        )
        """
    )

    # Future ML model information
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS ml_models
        (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            model_name TEXT,
            version TEXT,
            trained_on TEXT,
            training_samples INTEGER
        )
        """
    )

    conn.commit()
    conn.close()


def save_alert(alert):

    from datetime import datetime

    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute(
        """
        INSERT INTO alerts
        (
            type,
            ip,
            attempts,
            risk_score,
            severity,
            detection_method,
            created_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        (
            alert["type"],
            alert["ip"],
            alert["attempts"],
            alert.get("risk", 0),
            alert["severity"],
            alert.get("detection_method", "Rule Engine"),
            datetime.now().isoformat()
        )
    )

    conn.commit()
    conn.close()
